### PR TITLE
Wfp merge reassign all contacts into main

### PR DESCRIPTION
**Pull request by lperson**
@deasterdaywfp @joemcl This branch fixes the errors introduced in the last merge, hopefully.

### CODE REVIEW

**Comment by joemcl** [comment]
Thanks @lperson, @deasterdaywfp I'll merge and test it late tonight.

**Comment by joemcl** [comment]
Hey @lperson sorry but I created a merge conflict in https://github.com/WorkingFamilies/Spoke/pull/68 - I updated our opt out message with https://github.com/WorkingFamilies/Spoke/pull/69 - if you could pls resolve and obv keep the updated opt out message then I'll merge

**Comment by joemcl** [comment]
And I'll test this as-is on our staging Spoke, which won't have the same merge conflict..

**Comment by lperson** [comment]
@joemcl I fixed the conflict.

**Comment by joemcl** [comment]
@lperson thanks so much, I'll spin it up later tonight, cc: @deasterdaywfp

**Pull request merged**
